import type { MetadataRoute } from "next";

import { THEME_COLORS } from "@/lib/theme/theme";

/**
 * Served at `/manifest.webmanifest`. `start_url` points at the dashboard rather
 * than the marketing landing page so an installed copy opens on the ledger; an
 * unauthenticated launch still lands on sign-in through the usual proxy
 * redirect, which keeps the installed and browser experiences identical.
 *
 * Icons are generated by `scripts/generate-pwa-icons.mjs`. The maskable pair is
 * opaque with the mark inside the central 80% safe zone so Android's adaptive
 * mask cannot clip it.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/",
    name: "Budget App",
    short_name: "Budget App",
    description:
      "A self-hosted, read-only family budgeting app for Canadian households.",
    lang: "en-CA",
    dir: "ltr",
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",
    background_color: THEME_COLORS.light,
    theme_color: THEME_COLORS.light,
    categories: ["finance", "productivity"],
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
